---
- name: Dockerインストール
  yum: name=docker-io state=latest

- name: DockerDNS設定
  copy: src=./files/docker/docker.conf dest=/etc/sysconfig/docker mode=0644

- name: Dockerサービス起動
  service: name=docker enabled=yes state=started

- name: Dockerファイル設置
  git: repo=https://github.com/aozora0000/jenkins-ci.git dest=/usr/local/src/docker

- name: Docker再起動(DNS設定の読み込み)
  service: name=docker state=restarted

- name: jenkins-ciイメージのpull
  command: docker pull aozora0000/{{item}}
  with_items:
      - jenkins-ci-base
      - jenkins-ci-php
      - jenkins-ci-node
      - jenkins-ci-perl
