---
- name: Dockerインストール
  yum: name=docker-io state=latest

- name: DockerDNS設定
  copy: src=./files/docker/docker.conf dest=/etc/sysconfig/docker mode=0644

- name: Dockerサービス起動
  service: name=docker enabled=yes state=started

- name: Dockerファイル設置
  copy: src=./files/script/docker dest=/usr/local/src mode=0755

- name: Docker再起動(DNS設定の読み込み)
  service: name=docker state=restarted

- name: Dockerイメージのビルド
  docker_image: path=/usr/local/src/docker/{{item}} name={{item}} state=build
  with_items:
      - jenkins-ci-base
      - jenkins-ci-php
